
<div id="container" class="inner sub-page clearfix"> <!-- the inner pages have the "sub-page clearfix" classes added to the container div -->
    <?php include_once(APPLICATION_PATH.'/modules/default/views/scripts/includes/breadcrumb.phtml'); ?>
    <?php include_once(APPLICATION_PATH.'/modules/default/views/scripts/includes/sidebar.phtml'); ?>

    <div class="col-style2 float-right">
        <h1><?php echo $this->project->title; ?></h1>
        <?php echo $this->project->description; ?>
        <img src="images/test/inner.jpg" alt="" />
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec in ipsum est, quis porta elit. Donec ut tellus nunc, sed tempus neque. Quisque vel neque eget nibh malesuada vehicula.</p>
        <p>Etiam risus lectus, porttitor in posuere id, posuere in tellus. Integer facilisis libero a sapien fermentum porttitor a in libero. Etiam nec lectus id justo tempor blandit a quis massa. Suspendisse id convallis augue.</p>

        <h2>Second title</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec in ipsum est, quis porta elit. Donec ut tellus nunc, sed tempus neque. Quisque vel neque eget nibh malesuada vehicula. Etiam risus lectus, porttitor in posuere id, posuere in tellus. Integer facilisis libero a sapien fermentum porttitor a in libero.</p>
        <p>Etiam nec lectus id justo tempor <a href="#">blandit a quis massa</a>. Suspendisse id convallis augue. In egestas elementum purus, in adipiscing tortor iaculis in. Maecenas suscipit luctus ornare.</p>
        <p>Etiam tincidunt lobortis nisi eget laoreet. Pellentesque mauris lorem, viverra eu elementum sed, dapibus et ipsum. Morbi tincidunt tortor a urna lacinia volutpat. Donec aliquam, dui vel ornare aliquet, dolor elit vulputate purus, vitae.</p>

        <h2>Related links</h2>
        <a href="#">Lorem ipsum dolor sit amet, consectetur adipiscing elit</a>
        <br />
        <a href="#">Donec in ipsum est, quis porta elit</a>
        <br />
        <a href="#">Donec ut tellus nunc, sed tempus neque</a>
        <br />
        <a href="#">Quisque vel neque eget nibh malesuada vehicula.</a>
    </div>

</div>
<!-- ============ END container ============= -->
