
<div id="container" class="inner sub-page clearfix"> <!-- the inner pages have the "sub-page clearfix" classes added to the container div -->
    <?php include_once(APPLICATION_PATH.'/modules/default/views/scripts/includes/breadcrumb.phtml'); ?>
    <?php include_once(APPLICATION_PATH.'/modules/default/views/scripts/includes/sidebar.phtml'); ?>

    <div class="col-style2 float-right">
        <h1>Our projects</h1>

        <?php $count = 0; ?>
        <?php foreach($this->projects as $project): ?>
            <?php $odd = ($count++ % 2 == 0)? 'odd' : 'even'; ?>
            <div class="projects <?php echo $odd; ?> clearfix">
                <img style="width: 246px; height: 165px;" src="<?php echo $this->baseUrl("upload/images/") . $project['featured'];?>" alt="" />
                <div class="details">
                    <h2><?php echo $project['title']; ?></h2>
                    <p><?php echo $project['excerpt']; ?></p>
                    <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'project', 'action' => 'view', 'project_id' => $project['id']), null, true); ?>">
                        READ MORE &raquo;
                    </a>
                </div>
            </div>
            <div class="xl-space"></div>

        <?php endforeach; ?>

        <div class="xl-space"></div>
    </div>

</div>
<!-- ============ END container ============= -->
