
    <div id="edit-menu">
        <h2>Edit Menu Item</h2>
        <form method="post" action="/admin/menu/edit/">
            <p>
                <label for="menu_title">Title</label>
                <input type="text" name="title" id="menu_title" value="<?php echo $this->menu->title; ?>">
            </p>
            <p>
                <label for="menu_url">URL</label>
                <input type="text" name="url" id="menu_url" value="<?php echo $this->menu->url; ?>">
            </p>
            <p>
                <label for="menu_class">Class</label>
                <input type="text" name="class" id="menu_class" value="<?php echo $this->menu->class; ?>">
            </p>
            <input type="hidden" name="menu_id" value="<?php echo $this->menu->id; ?>">
        </form>
    </div>

