<div class="col-style1 float-left">
    <div class="inner-box contextual-box"> <!-- this is the contextual menu -->
        <h5>Site sections</h5>
        <ul>
            <li>
                <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'page', 'action' => 'view', 'page_id' => 7), null, true);?>">
                    About Kusasa
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'page', 'action' => 'view', 'page_id' => 10), null, true);?>">
                    Services
                </a>
                <?php if($this->controllerID == 'page' && ($this->pageID == 10 || ($this->pageID <= 6 && $this->pageID >= 0))): ?>
                <ul>
                    <?php foreach($this->services as $service): ?>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'page', 'action' => 'view', 'page_id' => $service['id']), null, true);?>">
                                <?php echo $service['title']; ?>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
                <?php endif; ?>
            </li>
            <li>
                <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'project', 'action' => 'list'), null, true);?>">
                    Our projects
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'project', 'action' => 'exclusive'), null, true);?>" style='width: 140px'>
                    Exclusive Products
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'page', 'action' => 'view', 'page_id' => 8), null, true);?>">
                    Meet the Team
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'page', 'action' => 'view', 'page_id' => 9), null, true);?>">
                    Contact us
                </a>
            </li>
        </ul>
    </div> <!-- END contextual menu -->

    <div class="xl-space"></div> <!-- after every box, EXCEPT for the last one, use div xl-space -->

    <div class="inner-box related-box"> <!-- related stuff -->
        <h5>Our latest projects</h5>
        <ul>
            <?php foreach($this->latestProjects as $latestProject): ?>
                <li>
                    <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'project', 'action' => 'view', 'project_id' => $latestProject['id']), null, true);?>">
                        <?php echo $latestProject['title']; ?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
        <div class="space"></div>
        <a class="padding-l18" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'project', 'action' => 'list'), null, true);?>">See all the projects</a>
    </div> <!-- END related stuff -->

</div>