<div class="col-style1 float-left">
    <div class="inner-box contextual-box"> <!-- this is the contextual menu -->
        <h5>Site sections</h5>
        <ul>
            <li>
                <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'page', 'action' => 'view', 'page_id' => 7));?>">
                    About Kusasa
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'page', 'action' => 'view', 'page_id' => 10));?>">
                    Services
                </a>
                <ul>
                    <li>
                        <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'page', 'action' => 'view', 'page_id' => 1));?>">
                            Development facilitation
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'page', 'action' => 'view', 'page_id' => 2));?>">
                            Project & Grant Funding
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'page', 'action' => 'view', 'page_id' => 3));?>">
                            Project Feasibilities
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'page', 'action' => 'view', 'page_id' => 4));?>">
                            Design Management
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'page', 'action' => 'view', 'page_id' => 5));?>">
                            Project Management
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'page', 'action' => 'view', 'page_id' => 6));?>">
                            Site Management
                        </a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#">
                    Our projects
                </a>
            </li>
            <li>
                <a href="#" style='width: 140px'>
                    Exclusive Products
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'page', 'action' => 'view', 'page_id' => 8));?>">
                    Meet the Team
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'page', 'action' => 'view', 'page_id' => 9));?>">
                    Contact us
                </a>
            </li>
        </ul>
    </div> <!-- END contextual menu -->

    <div class="xl-space"></div> <!-- after every box, EXCEPT for the last one, use div xl-space -->

    <div class="inner-box related-box"> <!-- related stuff -->
        <h5>Our latest projects</h5>
        <ul>
            <li>
                <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'project', 'action' => 'view', 'project_id' => 4));?>">
                    Gatwick Multi Storey Car Park
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'project', 'action' => 'view', 'project_id' => 5));?>">
                    Retail Projects
                </a>
            </li>
            <li>
                <a href="#">Domestic Projects no. 1</a>
            </li>
            <li>
                <a href="#">Domestic Projects no. 2</a>
            </li>
            <li>
                <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'project', 'action' => 'view', 'project_id' => 3));?>">
                    Boris Bikes in London
                </a>
            </li>

        </ul>
        <div class="space"></div>
        <a class="padding-l18" href="#">See all the projects</a>
    </div> <!-- END related stuff -->

</div>