<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Kusasa Administration Panel</title>
    <script type="text/javascript">
        var BASE_URL = '<?php echo $this->baseUrl(); ?>';
    </script>

    <?php
    $this->headLink()->appendStylesheet($this->baseUrl('/css/admin.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('/css/jquery-ui-1.8.18.custom.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('/css/jquery.ui.tooltip.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('/css/jquery.fancybox-1.3.4.css'));
    echo $this->headLink();

    $this->headScript()->appendFile($this->baseUrl('/js/jquery.js'));
    $this->headScript()->appendFile($this->baseUrl('/js/jquery-ui-1.8.18.custom.min.js'));
    $this->headScript()->appendFile($this->baseUrl('/js/jquery.fancybox-1.3.4.pack.js'));
    $this->headScript()->appendFile($this->baseUrl('/js/scripts.js'));
    $this->headScript()->appendFile($this->baseUrl('/js/validations.js'));

    //cluetip
    $this->headScript()->appendFile($this->baseUrl('/js/jquery.ui.widget.js'));
    $this->headScript()->appendFile($this->baseUrl('/js/jquery.ui.position.js'));
    $this->headScript()->appendFile($this->baseUrl('/js/jquery.ui.tooltip.js'));
    echo $this->headScript();
    ?>

</head>

<body>
<div id="header">
    <div class="head"> <!-- *** head layout *** -->
        <div class="head_top">
            <div class="topbuts">
                <ul class="clearfix">
                    <li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'login', 'action' => 'logout'), null, true); ?>" class="red">Logout</a></li>
                </ul>

            </div>
            <ul class="menu clearfix">
                <li><a href="<?php echo $this->url(array('module'=>'admin', 'controller'=>'index','action'=>'dashboard'), null, true); ?>">Dashboard</a></li>
                <li>
                    <a href="<?php echo $this->url(array('module'=>'admin', 'controller'=>'page','action'=>'index'), null, true); ?>">Pages</a>
                    <div class="dropdown">
                        <ul>
                            <li>
                                <a href="<?php echo $this->url(array('module'=>'admin', 'controller'=>'page','action'=>'index'), null, true); ?>">Pages</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url(array('module'=>'admin', 'controller'=>'pageCategory','action'=>'index'), null, true); ?>">Categories</a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li>
                    <a href="<?php echo $this->url(array('module'=>'admin', 'controller'=>'project','action'=>'index'), null, true); ?>">Projects</a>
                    <div class="dropdown">
                        <ul>
                            <li>
                                <a href="<?php echo $this->url(array('module'=>'admin', 'controller'=>'project','action'=>'index'), null, true); ?>">Projects</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url(array('module'=>'admin', 'controller'=>'projectCategory','action'=>'index'), null, true); ?>">Categories</a>
                            </li>
                        </ul>
                    </div>
                </li>

                <li>
                    <a href="<?php echo $this->url(array('module'=>'admin', 'controller'=>'menu','action'=>'index'), null, true); ?>">Menu</a>
                </li>

                <li class="back" style="float: right;"><a class="button yellow" href="<?php echo $this->url(array('module'=>'default', 'controller'=>'index','action'=>'index'), null, true); ?>">Back to site</a></li>
            </ul>
            <div class="logo clearfix">
                <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'index', 'action' => 'index')); ?>">
                    <img style="width: 260px;" src="<?php echo $this->baseUrl(); ?>/images/kusasa.png" alt="" />
                </a>
            </div>

        </div>


    </div>
</div>


<div id="content">
    <div class="main-wrap">
        <div id="messages" class="page clearfix"><?php //$this->messenger(); ?></div>
        <div class="content-box">
            <div class="box-body">
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
    </div>
</div>


</body>
</html>
