<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Kusasa</title>

    <?php
    $this->headLink()->appendStylesheet($this->baseUrl('/css/style.css'));
    echo $this->headLink();
    $this->headScript()->appendFile($this->baseUrl('/js/jquery.js'));
    echo $this->headScript();
    ?>
</head>

<body>
<?php echo $this->layout()->content; ?>
</body>
</html>
