
<div id="container" class="inner sub-page clearfix"> <!-- the inner pages have the "sub-page clearfix" classes added to the container div -->
    <?php include_once(APPLICATION_PATH.'/modules/default/views/scripts/includes/breadcrumb.phtml'); ?>
    <?php include_once(APPLICATION_PATH.'/modules/default/views/scripts/includes/sidebar.phtml'); ?>

    <div class="col-style2 float-right">
        <h1><?php echo $this->title; ?></h1>
        <?php echo $this->content; ?>
    </div>

</div>
<!-- ============ END container ============= -->
