<div class="box-header clearfix">
    <a class="button yellow" style="float:right; margin: 5px 10px 0 0"
       href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'project', 'action' => 'add')); ?>">
        Add a new project
    </a>
    <h2><?= "Projects list"; ?></h2>

</div>
<div class="box-wrap clearfix">
    <div id="table">
        <?php if ($this->countProjects > 0): ?>
        <table class="style1" cellpadding="0" cellspacing="0" summary="">
            <thead>
            <tr>
                <th width="30%">Title</th>
                <th width="20%">Category</th>
                <th width="45">Description</th>
                <th width="5%">Actions</th>
            </tr>
            </thead>
            <tbody>
                <?php foreach ($this->projects as $project): ?>
                    <tr>
                        <td>
                            <?php echo $project['title']; ?>
                        </td>
                        <td>
                            <?php echo $project['category_name']; ?>
                        </td>
                        <td>
                            <?php echo $project['excerpt']; ?>
                        </td>
                        <td align='center'>
                            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'project', 'action' => 'edit', 'project_id' => $project['id'])); ?>">
                                <img src="<?php echo $this->baseUrl(); ?>/images/admin/ico_edit_16.png" class="icon16 fl-space2" alt="" title="edit" />
                            </a>
                        </td>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>

        <?php endif; ?>

    </div>
</div>